### ISSUE TITLE
Jmeter shows only one folder in open dialog

### ISSUE THREAD

**Issue by nelson777** [flathub/org.apache.jmeter#1]
Hello,

My Flatpak version o JMeter shows only one folder in open dialog: Documents. Nothing else.

I'm on Linux Mint 21.

Does anyone knows a way of fixing this ?

**Comment by prodrigestivill** [comment]
as stated in the README, by default only the Documents folder has permissions.

If you want to change the default permissions use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) and allow to acces to the folder you need or to all your home.
