### ISSUE TITLE
Cannot save data 

### ISSUE THREAD

**Issue by hhyyrylainen** [flathub/org.apache.jmeter#15]
I see just my "home" folder in the save and load dialogs. Which is just an empty folder.

This wasn't a very nice surprise to me to lose the tests I wrote and "saved". Would be very nice to actually get a warning or error telling you that the "home" folder you see and can write to will get deleted.

Also it is not clear to me which folders I can save things safely to. I saw https://github.com/flathub/org.apache.jmeter/issues/1 which seems to say that there's some folder I can save to.  I tried a few folders but it doesn't seem any result in the files being actually saved. At least I can't find any of them in `~/.var/app/org.apache.jmeter`. Even if it seems some files persist at least for a bit between reopening jmeter.

**Comment by prodrigestivill** [comment]
I'm sorry you lost some work.

The reason this flatpak is setup this way is that the Flathub policy regarding permissions. Their main idea is to only allow the minimum permissions requiered and in the case of this application it has been decided it only requires acces to the Documents folder by default.

To avoid probles this information has been exposed in the [Flathub app page](https://flathub.org/apps/org.apache.jmeter) description and in [README.md](https://github.com/flathub/org.apache.jmeter#readme) in this repository.

I undestand you saved your files in another folder and lost your work once the application had stop. This flatpak is using the official JMeter builds. Adding a warning when saving in a tmpfs should idealy be implemented in the main app itself in their github repo.

Another option is to wide the default permissions to allow other folders by default.

For now you can change this app permissions using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), there you can allow acces to the folder you need or to all your home.

**Comment by hhyyrylainen** [comment]
The problem is that this is what I see when trying to save something:
![kuva](https://github.com/flathub/org.apache.jmeter/assets/3796411/04e8c5fa-82d3-4293-8307-8c919e248f0c)

If I manually create a new folder called "Documents" and save inside that, the file and the folder still disappear if I restart the program.

**Comment by prodrigestivill** [comment]
What desktop environment are you using?

The xdg-documents folder (usually `~/Documents`) should be exported and usable in your virtual flatpak home.

Can you run: `xdg-user-dir`

**Comment by hhyyrylainen** [comment]
```sh
$ xdg-user-dir
/home/hhyyrylainen
```

I'm running GNOME desktop (Fedora 38). I have my OS language set to Finnish so my documents folder is called `Asiakirjat` . Though as there are various programs that don't work correctly I have a symlink called `Documents` pointing to that real location.

And one more thing that could cause problems is that I have my bulk data storage on a different partition so `~/Asiakirjat` links to a different folder under `/mnt/`

**Comment by hhyyrylainen** [comment]
Ah, I see. So likely it is that my XDG documents dir is messed up. Thanks for pointing me in the right direction. 

This is the first time I've ran into a problem with my recreated folders. I guess if I had more experience with flatpak I would have ran into this issue eventually with some other software.

Just running:
```
xdg-user-dirs-update --set DOCUMENTS ~/Asiakirjat
```
made it work. I'll try to fix the rest of the folder paths as well. Thanks for the help.
