### ISSUE TITLE
Support JSR223 JavaScript

### ISSUE THREAD

**Issue by nelson777** [flathub/org.apache.jmeter#2]
I have a perfectly working JMeter script that uses a JSR223 sampler to calculate some variables.

Now when I install JMeter via Flatpak this module simply doesn't run (or at least the variables aren't there). I tried to allow all permissions on Flatseal and the result was the same.

Anyone knows why is this ?

**Comment by nelson777** [comment]
Hi. Thanks for answering. In JSR223 I'm using javascript.

I think the best is providing a example project. In this link I sent you the project file:

https://filetransfer.io/data-package/JnpzFqJs#link

This is a simple project with only only one https request to google.com where I included the JSR223 module with my code inside.
See that it calculates 2 codes: statusCode and nonceCode. It's just 2 UUIDs.

I have included a debug sampler. To see the problem, please run this script in a non-flatpak installed JMeter. You will see that in  View Result Tree you have the Debug item. Please select it and then the response data tab. Please note that there are 2 variables in this window that should be more or less like this:

    nonceCode=b6a40f01-9b1e-4cb9-81e9-407cee2349ea
    stateCode=d5ad1681-86ad-40cd-8e70-0f253888cb9c

Obviously the numbers will change in each run.

Now try the same procedure in a Flatpak installed JMeter and you'll see the numbers aren't there.

**Comment by prodrigestivill** [comment]
I haven't tried yet, but could it be related with this [answer](https://stackoverflow.com/a/64911353) ([JEP](https://openjdk.org/jeps/372))?

If I understand it correctly to fix this it would mean downgrading JDK to use version 8 instead of the latest supported 17.

**Comment by nelson777** [comment]
AFAIU the answer, what it says is that since JMeter 3.1 the module I'm using is the one that should be used.
But it's certainly not related to the downgrade of JDK because I'm using Openjdk version "11.0.15" 2022-04-19 to run non-flatpak installed JMeter. So it's pretty up-to-date.

About language "not being in the list". I didn't understand what you mean. Can you elaborate plz ? What list ?

**Comment by nelson777** [comment]
AFAIU the answer, what it says is that since JMeter 3.1 the module I'm using is the one that should be used.
But it's certainly not related to the downgrade of JDK because I'm using Openjdk version "11.0.15" 2022-04-19 to run non-flatpak installed JMeter. So it's pretty up-to-date.

About language "not being on the list" I found that strange because javascript is in the list. So I opened non-flatpak installed JMeter and checked the languages list. Javascript it's there. Take a look: https://imgur.com/a/TiMMZn1

Please note that it's the same JMeter version that Flatpak installs (5.5). If you check the list you'll see there are entries for Javascript, emcascript, js and nashorn that aren't present in Flatpak's version. So Flatpak installed JMeter removes all languages derived from EMCAScript. 

I tested using other language (groovy script) and it correctly added the vars to the script. So I can translate the script for some supported script language. But I guess I'll probably won't be the only one using Javascript in a script. Although my script is really simple and easy to translate other scripts maybe far more complex. 
This can be an adoption drawback. Maybe it would be better to investigate why javascript is removed from the list ?

**Comment by prodrigestivill** [comment]
As the JEP says, javascript has been removed since Java 15, and hasn't been recommended by JMeter since 3.1 for intensive load testing.

I'm downgrading JMeter Flatpak to use OpenJDK 11 for some months, but I understand it will need to upgrade to 17 before next September, so from then no more javascript will be supported.

**Comment by nelson777** [comment]
I see. As you said with this new version the languages reapeared. I took the decision to rewrite the script to update to newer java versions. Please maintain as it is. You can't stop the time :) I just needed to know why this was happening. Thanks for your help.

**Comment by prodrigestivill** [comment]
Don't worry, OpenJDK is still maintained for some months, no problem in using that for some time, but eventually we will switch to next 17-LTS or 21-LTS.

In any case, thanks for the report!

**Comment by nelson777** [comment]
NP. I was trying to translate the script when I realize Groovy has native UUID creation. So my script shortened to 2 lines:

    vars.put("stateCode", UUID.randomUUID().toString());
    vars.put("nonceCode", UUID.randomUUID().toString());

much better. Great result. Again thanks.

**Comment by prodrigestivill** [comment]
Updated to OpenJDK 17, but added mozilla rhino engine as a JSR223.
More info on changes in PR #21.
